### ISSUE TITLE
SUDAO-IPs Update

### ISSUE THREAD

**Issue by Livedollar** [SuperUMAn-DAO/SUDAO-IPs#2]
### TODO: 
 

- [ ] Update missing improvement proposals.
The proposals can be found on the SuperUMAn DAO Discourse, Snapshot or SnapshotSQL.

- [ ] Reference check with corresponding doc to be certain it has been added or amended.

 - [ ]  A README. to help guide community members around who may be unfamiliar with the SUDAO and Github. 
 For the SUDAO-IPs repo and wherever else is warranted.
